/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'warm-ecru': '#F4EFEA',
        'tertiary': '#000601',
        'surface-container-lowest': '#ffffff',
        'espresso-deep': '#161311',
        'on-secondary-fixed': '#2c1600',
        'on-surface-variant': '#4d4540',
        'background': '#fcf9f3',
        'on-primary-fixed-variant': '#4b4642',
        'outline-variant': '#d0c4bd',
        'on-tertiary-fixed-variant': '#3c4b3a',
        'primary-container': '#211d1a',
        'primary-fixed-dim': '#cdc5c0',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'soft-linen': '#EDE6DE',
        'on-background': '#1c1c18',
        'on-primary-fixed': '#1f1b18',
        'tertiary-fixed-dim': '#bbcbb6',
        'on-secondary-container': '#79542c',
        'primary': '#060403',
        'inverse-primary': '#cdc5c0',
        'outline': '#7e756f',
        'on-primary-container': '#8b8480',
        'tertiary-container': '#142113',
        'secondary': '#7c572e',
        'surface': '#fcf9f3',
        'on-secondary-fixed-variant': '#613f19',
        'surface-bright': '#fcf9f3',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'muted-border': '#E3DCD3',
        'inverse-on-surface': '#f3f0ea',
        'secondary-container': '#fecb99',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e5e2dc',
        'surface-dim': '#dcdad4',
        'primary-fixed': '#eae1dc',
        'on-tertiary-container': '#7a8a77',
        'inverse-surface': '#31312d',
        'on-surface': '#1c1c18',
        'surface-variant': '#e5e2dc',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#d7e7d1',
        'on-tertiary-fixed': '#111f11',
        'secondary-fixed': '#ffdcbd',
        'secondary-fixed-dim': '#efbd8c',
        'surface-container-low': '#f6f3ed',
        'surface-tint': '#635d59',
        'terracotta': '#C46851',
        'surface-container': '#f0eee8',
        'on-error-container': '#93000a'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'space-md': '1.25rem',
        'margin-mobile': '1.25rem',
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-lg': '2rem',
        'gutter-mobile': '1rem',
        'margin': '3rem',
        'gutter': '1.5rem',
        'space-xl': '3.5rem'
      },
      fontFamily: {
        'headline-lg-mobile': ['Newsreader', 'serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'headline-sm': ['Newsreader', 'serif'],
        'headline-lg': ['Newsreader', 'serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-xl-mobile': ['Newsreader', 'serif'],
        'headline-md': ['Newsreader', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'headline-xl': ['Newsreader', 'serif'],
        'title-lg': ['Manrope', 'sans-serif'],
        'title-md': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif']
      },
      fontSize: {
        'headline-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '30px', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-xl-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '30px', fontWeight: '400' }],
        'headline-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }]
      }
    }
  },
  plugins: []
};
